item {
    id: 1
    name: 'Huevo'
}

item {
    id: 2
    name: 'Jugo de naranja'
}

item {
    id: 3
    name: 'Pera'
}

item {
    id: 4
    name: 'Repollo'
}

item {
    id: 5
    name: 'Tomate'
}